name: Scheduled Python Workflow

on:
  # schedule:
  #   - cron: '*/5 * * * *'  # Set your desired cron schedule here to run every 5 minutes
  workflow_dispatch:  # Enable the workflow to be manually triggered

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Choose the Python version you want to use

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install dependencies
      run: |
        bash install.sh
        
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "insta.json"
        json: ${{ secrets.COOKIE }}
        dir: "."
        
    - name: Run Python script
      env:
          FILE_ID: ${{ secrets.FILE_ID }}
          DAY: ${{ vars.DAY }}
          TAG: ${{vars.TAG}}
          # AGENCIES: ${{ secrets.AGENCIES }}
      run: |
        python main.py

    - name: Commit and Push The Results From Python Selenium Action
      run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add ./screen*
         git commit -m "GitHub Actions Results added"
         git push

    # - name: Commit files
    #   run: |
    #     git config --local user.email "${{ secrets.GIT_EMAIL }}"
    #     git config --local user.name "${{ secrets.GIT_NAME }}"
    #     git add .
    #     git commit -m "Updated Proxies"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
